-- Event Ticket Booking System - MySQL Schema
-- Database: event_booking_db

CREATE DATABASE IF NOT EXISTS event_booking_db;
USE event_booking_db;

CREATE TABLE IF NOT EXISTS users (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    phone       VARCHAR(20)  NOT NULL UNIQUE,
    role        ENUM('USER', 'ADMIN') NOT NULL DEFAULT 'USER'
);

CREATE TABLE IF NOT EXISTS events (
    id              BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_name      VARCHAR(255)   NOT NULL,
    category        VARCHAR(100)   NOT NULL,
    location        VARCHAR(255)   NOT NULL,
    event_date      DATETIME       NOT NULL,
    end_date        DATETIME       NOT NULL,
    status          ENUM('UPCOMING', 'SOLD_OUT', 'EXPIRED') NOT NULL DEFAULT 'UPCOMING',
    version         BIGINT         NOT NULL DEFAULT 0,
    total_seats     INT            NOT NULL,
    available_seats INT            NOT NULL,
    ticket_price    DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    booking_reference VARCHAR(50)    NOT NULL UNIQUE,
    user_id           BIGINT         NOT NULL,
    event_id          BIGINT         NOT NULL,
    tickets_booked    INT            NOT NULL,
    booking_date      DATETIME       NOT NULL,
    total_amount      DECIMAL(10, 2) NOT NULL,
    status            ENUM('BOOKED', 'CANCELLED') NOT NULL DEFAULT 'BOOKED',
    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_booking_event FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE INDEX idx_bookings_user ON bookings(user_id);
CREATE INDEX idx_bookings_event ON bookings(event_id);
CREATE INDEX idx_bookings_status ON bookings(status);

-- Default admin (password: admin123 - BCrypt hash generated by Spring Boot on startup)
-- Admin user is auto-created by DataInitializer on first run
